### ISSUE TITLE
Large album completely freezes the app in the browser

### ISSUE THREAD

**Issue by KucharczykL** [navidrome/navidrome#1186]
### Description

I have a (custom) album that consists of roughly 300 songs and when I open it in Navidrome, after a moment the UI freezes and the only solution is closing the tab or even a browser.

### Expected Behaviour

Opening an album with large amount of songs doesn't freeze the UI.

### Steps to reproduce

1. Open an album with a lot of songs (I have 272).
2. Wait or scroll around.
3. UI slows down and eventually freezes.

### Platform information

 - Navidrome version: 0.43.0 (d9f26826)
 - Browser and version: 89.0 (64-bit)
 - Operating System: openSUSE Tumblweed, Navidrome is running in Docker on a Debian (OpenMediaVault) machine

### Additional information

Any other information that may be relevant or give context to the problem.

The tab is frozen:
![image](https://user-images.githubusercontent.com/31072879/122386000-b4678480-cf6d-11eb-8fd0-3959a8745c6b.png)

I don't think there's anything in the logs but I set them to trace and uploaded them here anyway:

[_navidrome_logs(1).txt](https://github.com/navidrome/navidrome/files/6669701/_navidrome_logs.1.txt)

**Comment by LucaDLL** [comment]
Just wanted to add that I have the same problem... for me, albums/playlists under 30 songs are safe, albums/playlist with 30 to 50 songs occasionally freeze the tabs, and then I have a playlist with 100 songs which almost always freezes the tab... To play it I usually enter the playlist, press the shuffle button, and then quickly get back to any page with a few entries (like the random albums page); managing the playlist (removing songs for instance) is basically impossible. My logs are pretty much like the OP's ones.

### Platform information

 - Navidrome version: v0.43.0
 - Browser and version: Firefox v89.0.1 on both Windows 10 and Kubuntu 20.10
 - Operating System: Ubuntu Server 20.04.2 LTS, using a binary.
 
I don't know if the machine capabilities play a role in this... Windows 10 runs on a i3-3220 desktop with 8 GB of RAM, Kubuntu 20.10 on a Thinkpad X1 Carbon 3rd Gen (i5-5300 with 8 GB of RAM), the server has a Pentium Dual Core E2200 with 2 GB of RAM. I read that this problem should be solved by infinite scrolling, in the mean time maybe introducing an item per page selector with the possibility of selecting 30/50/1000 items per page could be a good stopgap measure? Or it would harm usability too much for the people which do not have this problem? Kind regards and keep up the good work!

**Comment by ToadCast** [comment]
Hi, I'll try to reproduce with the same version but honestly I have no issue to load an album with 414 Songs, 1:12:05:34 long and 9.1 GB all in FLAC 16-bits.

### Platform information
- Navidrome version: v0.42.0
- Browser and version: Firefox v89.0.2 on both Windows 10 and Ubuntu 18.04.5
- Operating System: Debian 10, using Docker

**Comment by nicholas-robertson** [comment]
I have this issue with a large playlists. The interface hang and is unusable after the playlist page is opened.

**Comment by andrewzah** [comment]
I've had this issue as well, with a 4-CD album / 98 songs. After a little bit the UI completely freezes and I have to load a new tab.

* Navidrome version: `0.44.1-SNAPSHOT (c0fc36da)`  in docker on debian 10
* Browser and version: `Firefox 78.11.0esr`
* Operating System: `Debian 10`

**Comment by deluan** [comment]
@KucharczykL and all: I just tried with Firefox version 89.0.2 (same version @ToadCast is using and didn't have the issue), with a 280 songs album and was not able to reproduce this as well. Can you please try upgrading your browsers to the latest version? Also is it possible to test with a different browser?

@nicholas-robertson How large is the playlist? Can you also try upgrading to 89.0.2?

**Comment by KucharczykL** [comment]
I just did a quick test with Firefox 90 and Chromium 92.

Firefox loaded the album and I could scroll freely without freezing but when I clicked on a song to play, it kept loading and eventually froze the app but not the browser. 

Chromium could both load and play a song but after 31 seconds of playback the app froze, too. I could still scroll the list but the playback controls were not interactive anymore. Funnily enough the spinning album cover animation still worked. When I clicked on another song the whole app froze completely.

**Comment by deluan** [comment]
Can you try with Navidrome 0.44.1? It fixes a bug in the Activity Panel that could cause this type of UI freezing.

**Comment by KucharczykL** [comment]
I am running 0.44.1 (fb183e58).

**Comment by deluan** [comment]
> I am running 0.44.1 ([fb183e5](https://github.com/navidrome/navidrome/commit/fb183e58e9ffc12a04d410621a2deeb547b9906f)).

Can you try disabling the activity panel, then?

**Comment by KucharczykL** [comment]
> > I am running 0.44.1 ([fb183e5](https://github.com/navidrome/navidrome/commit/fb183e58e9ffc12a04d410621a2deeb547b9906f)).
> 
> Can you try disabling the activity panel, then?

I can confirm setting ND_DEVACTIVITYPANEL to false fixes the freezes. The UI is still slower than usual, like clicking songs or buttons takes about a second to register, but at least it works now. Thanks! :grin:

**Comment by KucharczykL** [comment]
@deluan I am not sure whether I should keep the issue open or close it. For me, the main issue was fixed, even though I have to use a dev flag. However, there is still a slowdown but I think filing a separate issue to track that might be better. What do you think?

**Comment by nicholas-robertson** [comment]
> @nicholas-robertson How large is the playlist? Can you also try upgrading to 89.0.2?
798 songs. 

I can also confirm that adding `ND_DEVACTIVITYPANEL: "false"` to `docker-compose.yaml`.

**Comment by deluan** [comment]
Hey folks, for those still having this issue, I think I got a clue of what is happening. Can you please do a test for me?

Set `LogLevel="debug"`, set `DevActivityPanel=true`, restart Navidrome. When it freezes, take a look at the logs and find one or more messages like this:
```
Client added to event broker                  newClient="103a14e8-4ff4-48ff-9d39-966ef9f65de7 (admin - 127.0.0.1 - 1a5a2193-4d10-464d-b36b-55f3d2c109d7)" numClients=2
```

And please report in this thread what is the maximum `numClients` you can find in the logs. Thanks in advance for the help.

**Comment by KucharczykL** [comment]
For me `numClients` says `1`. The UI froze and after the current track completed, no more songs played.

**Comment by andrewzah** [comment]
On `0.45.0-SNAPSHOT (cf042ed8)` I've been unable to reproduce this issue with the dev activity panel enabled.

Large albums can take a few seconds to load and picking a new song has about ~1s delay, but there was no freezing or anything like before.

**Comment by Iwyil** [comment]
I am having the same issue. Both with Chromium and Firefox. I ma using a docker image, version 0.45.1 (when I downloaded it was the 'latest'). Setting `ND_DEVACTIVITYPANEL=false` make things run without problems.

> And please report in this thread what is the maximum numClients you can find in the logs. Thanks in advance for the help

For me `numClients` is `1`.

I don't know if it might help, but I have a performance profile of Chromium. The domain has been set to `music.example.com`
[profile-chromium-navidrome-0.45.1.zip](https://github.com/navidrome/navidrome/files/7070446/profile-chromium-navidrome-0.45.1.zip)

**Comment by pyluyten** [comment]
For what its worth i could reproduce the issue almost each time i play a track in one of my 150+ songs album. (I have several.) Setting DevActivityPanel="false" seems to help.

Navidrome 0.45.1 (c55e6590); direct install on Debian
I used navidrome before 0.45 and did not notice this bug


log at last crash but i am not sure to see what is relevant


sept. 20 17:50:01 debian navidrome[25871]: time="2021-09-20T17:50:01+02:00" level=info msg="Streaming file" artist="Maria João Pires" bitRa>
sept. 20 17:50:01 debian navidrome[25871]: time="2021-09-20T17:50:01+02:00" level=debug msg="HTTP: GET http://navidrome.XXXX.host/rest/st>
sept. 20 17:50:03 debian navidrome[25871]: time="2021-09-20T17:50:03+02:00" level=debug msg="HTTP: GET http://navidrome.XXXX.host/api/son>
sept. 20 17:50:03 debian navidrome[25871]: time="2021-09-20T17:50:03+02:00" level=debug msg="API: New request /rest/scrobble" client=Navidr>
sept. 20 17:50:03 debian navidrome[25871]: time="2021-09-20T17:50:03+02:00" level=info msg="Now Playing" artist="Maria João Pires" player=">
sept. 20 17:50:03 debian navidrome[25871]: time="2021-09-20T17:50:03+02:00" level=debug msg="API: Successful response" requestId=debian/rKu>
sept. 20 17:50:03 debian navidrome[25871]: time="2021-09-20T17:50:03+02:00" level=debug msg="HTTP: GET http://navidrome.XXXX.host/rest/sc>
sept. 20 17:50:22 debian navidrome[25871]: time="2021-09-20T17:50:22+02:00" level=debug msg="Scheduler: wake" now="2021-09-20 17:50:22.0074>
sept. 20 17:50:22 debian navidrome[25871]: time="2021-09-20T17:50:22+02:00" level=debug msg="Scheduler: run" entry=1 next="2021-09-20 17:51>
sept. 20 17:50:22 debian navidrome[25871]: time="2021-09-20T17:50:22+02:00" level=debug msg="Scanning folder" folder=/home/cloud/py/musique>
sept. 20 17:50:22 debian navidrome[25871]: time="2021-09-20T17:50:22+02:00" level=debug msg="Directory tree loaded from DB" elapsed=276.1ms>
sept. 20 17:50:22 debian navidrome[25871]: time="2021-09-20T17:50:22+02:00" level=debug msg="Processing changed folder" dir="/home/cloud/py>
sept. 20 17:50:22 debian navidrome[25871]: time="2021-09-20T17:50:22+02:00" level=debug msg="Finished reading directories from filesystem" >
sept. 20 17:50:22 debian navidrome[25871]: time="2021-09-20T17:50:22+02:00" level=debug msg="Finished deleted folders check" elapsed="805.0>
sept. 20 17:50:22 debian navidrome[25871]: time="2021-09-20T17:50:22+02:00" level=info msg="Finished processing Music Folder" added=0 delet>

**Comment by bbsixzz** [comment]
I just tried a playlist with 163 tracks and had no issues on a Pi Zero W running DietPi v7.6.2 Bullseye.

Linux DietPi 5.10.60+ #1449 Wed Aug 25 14:59:20 BST 2021 armv6l GNU/Linux
Navidrome 0.45.1 (c55e6590)

macOS Big Sur 11.6 (20G165)
Safari 15.0 (16612.1.29.41.4, 16612)

**navidrome.toml**
```
AuthRequestLimit = '5'
AuthWindowLength = '20s'
CoverArtPriority = 'embedded'
CoverJpegQuality = '100'
EnableFavourites = 'true'
EnableLogRedacting = 'true'
EnableStarRating = 'false'
EnableTranscodingConfig = 'false'
ImageCacheSize = '0'
LastFM.Enabled = 'false'
LogLevel = 'info'
Scanner.Extractor = 'taglib'
ScanSchedule = '0'
UILoginBackgroundUrl = ''
```

**Comment by WolfgangDpunkt** [comment]
I have observed the same problem, but only since I created a playlist with about 1200 entries using the new Smart Playlist feature.
The UI always freezes with very high CPU usage of the browser after some scrolling in this playlist.

But ND_DEVACTIVITYPANEL=false seems to have fixed the problem.

- Client: Firefox 94.0.1 (64-Bit) (but same behavior in Safari browser), macOS 10.15.7, 
- Server: navidrome 0.46.0-SNAPSHOT (8c7d95c1), Docker Image "deluan/navidrome:develop", Linux DietPi, Raspberry Pi 4

Thank you for further investigations.

**Comment by deluan** [comment]
Just an update on this issue: I'm trying some things to figure out what is the root cause of this. Can someone that had to set `DevActivityPanel` to false test the latest dev build with the flag set to true, please?

Direct link: https://nightly.link/navidrome/navidrome/workflows/pipeline/master/binaries.zip

Let me know if this build still causes high CPU and freezes. Thanks!

**Comment by durin42** [comment]
I haven't set anything about DevActivityPanel and I'm still seeing this with 2e1b985d30d38165a88207326f173fe89612efee which is from December 10th or so. Firefox on macOS Intel, but I'm happy to test on other platforms I've got around if that helps.

**Comment by deluan** [comment]
Can someone on this thread please confirm if the issue still exists in latest 0.47.5 version? Thanks!

**Comment by ParadingLunatic** [comment]
Looks like I might still be having the issue.  I thought I had the ND_DEVACTIVITYPANEL=FALSE set, but it looks like I have it set to ND_ACTIVITYPANEL=FALSE.  Froze up about 3 or 4 songs into a 2000+ song playlist (please don't judge me, I use it mainly to sync songs to my phone I like.  I restart my docker container with the environment set as ND_DEVACTIVITYPANEL....

Interesting...As I was typing this (about 3ish mins after it froze) it started back up...once again with the wrong env flag set.

**Comment by TheFlatworm** [comment]
I have an album with about 950 songs - it locks up the UI.
Version: 0.47.0-SNAPSHOT
<https://github.com/navidrome/navidrome/compare/v0.47.0...f84b5125>
 (f84b5125)

**Comment by skarrok** [comment]
Can confirm issue still exists on 0.47.5. Browser tab freezes after 10-30 seconds on large album page.

Version: 0.47.5 (86fe1e3b) on ArchLinux
Browser: Chrome 100.0.4896.60 (64bit) and Firefox 98.0.2 (64bit)
Album size: 200 songs

Settting DevActivityPanel to false fixes it.

**Comment by 3windmill** [comment]
Issue still exists on Debian  10 (buster) 32bit.
Browser  Firefox 99.0 (32 bit)

Settting DevActivityPanel to false fixes it.

**Comment by dmeador** [comment]
I'm experiencing the webui hang issue with large albums/playlists.
I just pulled the latest code (as of commit #1638) and buildall.

Reproducible on the first track played 100% of the time.  I can usually watch the position count and within 10-30 seconds, the position seconds will stop updating, which indicates that the problem will happen soon... the track will play for a little while longer and then eventually webui freezes.

Listening on up-to-date chrome browser on windows, connecting to navidrome server on ubuntu 20.04.

Setting DevActivityPanel=false in /var/lib/navidrome/navidrome.toml  config file fixes it (at least I get past the first track freeze) for me.  I can help debug logs / reports if you like, let me know what to look for.

**Comment by boydfields** [comment]
Experiencing exact same thing.  I have one particular album which has over 1800 songs which I appreciate is a special use case.  ND web and any iOS app crashes upon browsing the album.

**Comment by bbsixzz** [comment]
Server:
Navidrome 0.47.5 (86fe1e3b) 
Linux debian 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

Client:
macOS Big Sur 11.7
Safari Version 16.0 (16614.1.25.9.10, 16614)

Just ran into this while making a playlist with ~150 tracks from random albums.

`sudo systemctl restart navidrome.service `

That fixed it, for now.

**Comment by flo333** [comment]
Same problem for me on [0.47.5](https://github.com/navidrome/navidrome/releases/tag/v0.47.5) (86fe1e3b) using Firefox. Restarting the service only fixes it temporarily, the problem always returns...I'll try `ND_DEVACTIVITYPANEL`.

**Comment by boydfields** [comment]
ND is working well if I reduce the song count to around 100 per album or playlist. If I go beyond, front and back-end start to hang. For example, opening an album with more than 300 songs causes Firefox to use up all available RAM until it eventually crashes, taking my ND container with it. Only a hard restart resolves the problem. 

I am running ND on a RPI4. Could it be a lack of hardware resources on the server side? Please note; ND_DEVACTIVITYPANEL=false has no effect.

**Comment by Wiljaxelmaz** [comment]
I tried again today, I loaded my album with "572 Songs · 2:09:48:41 · 3.39 GB", it froze a bit for like 3 seconds, then loaded the songs and I could select few of them play them. I really don't get how this works 😒

**Comment by boydfields** [comment]
I set "ND_DEVFASTACCESSCOVERART=true" and adjusted all my embedded artwork to be reduced in resolution and file size (some of my cover art was in-excess of 500KB per file; now 500x500 at 80KB or less).

These two things have resolved the issues I was having with ND freezing and causing lock-ups upon opening large albums or playlists. I used mp3tag to process 4000+ albums.  Took a while but well worth it and quality has not suffered too much.

Hope this helps others.

**Comment by nekr0z** [comment]
I think I'm being hit with this issue also on modestly-sized albums (15 to 25 songs) in resource-limited environments (Firefox on a PC with only 3Gb RAM and other software running, a smart TV, etc.) Disabling the activity panel seems to help.

**Comment by deluan** [comment]
Can someone here please test the latest develop build with DevActivityPanel enabled (=true)? I did some work that may resolve this issue. Please give feedback

**Comment by KucharczykL** [comment]
Hello @deluan! I've just tried it on version 0.49.3 (8b93962f) and at first it seemed that it's completely fixed. However, after a few minutes the UI locked up again. My observation is that it takes much longer for that to happen than before, I've been scrolling a page with ~200 songs for around a minute and half until it froze. IIRC before it took a few seconds.

I think lists with ~100 songs are fixed, though, where before they would also cause this issue.

**Comment by deluan** [comment]
Thanks @KucharczykL. Yeah, I did some tweaking in 0.49.x versions, but I'd like to test the latest `develop` version, where I did some optimizations on the ActivityPanel. 

If anyone here is running the `develop` version, please update, re-enable the `DevActivityPanel` and give feedback.

**Comment by metalheim** [comment]
@deluan was able to break it in 0.49.3-SNAPSHOT (be12c12b)

1. opened an album with 757 songs (i know...) 
2. scrolled around a bit
3. first, some rows aren't rendered anymre
4. then the navidrome tab crashed

![image](https://github.com/navidrome/navidrome/assets/44159957/12d44173-db77-4df1-9a00-8a9546a7c25a)
[0.49.3-SNAPSHOT](https://github.com/navidrome/navidrome/compare/v0.49.3...be12c12b) (be12c12b)

**Comment by deluan** [comment]
Thanks @metalheim, I think we have two different but related issues here: Large albums like that causes the browser to freeze/crash because the way React renders grids and tables. I'm trying to address this in the new UI with a virtual grid (like virtuoso.dev)

The second issue is that in some circumstances the browser opens multiple EventStream connections (used by the ActivityPanel) with the server. This causes a high overhead of cpu usage, specially when a scan is happening and/or you have a medium to large list opened (sometimes it doesn't even matter the size of the list being viewed). This second issue is what I'm currently trying to resolve.

**Comment by metalheim** [comment]
@deluan i think i am affected by this very issue, or that it is at least releated.

Setting DevActivityPanel back to false resolves it for me and even that large album is perfectly usable (after a slightly longer initial load)

**Comment by deluan** [comment]
@metalheim Can you confirm that the freeze occurs when there's a scan in progress?

**Comment by metalheim** [comment]
my normal configuration is scanschedule set to @every 2m so kinda often.
I'll decrease scan frequency, re-enable DevActivityPanel and check back!

**Comment by metalheim** [comment]
@deluan yes the behaviour is linked to a scan running!

1. no scan running
    * was able to browse through that big album without the issue
    * Played some tracks from the middle of the big album, jumped to other albumst - all works fine.
    *  Tab has high-ish cpu usage, but that is expected with this many rendered elements
    * No freezes!
3. started a quick scan from Activity Panel 
    * tab freezes after ~10s. Music stops playing and all.
    * tab stops rendering and is generally completely unresponsive

**Comment by deluan** [comment]
Thanks for confirming this. Currently I'm sending one event for each folder processed during scan. I'll try to reduce this to one event every ~10 folders. If this also does not work, next thing I'll try is to replace SSE with WebSockets, which seems to be a more mature technology for this kind of communication.

I'll let you know when I work on this again. Thanks for your patience :)

**Comment by metalheim** [comment]
@deluan great!
i have 21562 folders, so it is probably choking on 21562 events then :D

**Comment by sebastianschauenburg** [comment]
> Thanks @metalheim, I think we have two different but related issues here: Large albums like that causes the browser to freeze/crash because the way React renders grids and tables. I'm trying to address this in the new UI with a virtual grid (like virtuoso.dev)
> 
> The second issue is that in some circumstances the browser opens multiple EventStream connections (used by the ActivityPanel) with the server. This causes a high overhead of cpu usage, specially when a scan is happening and/or you have a medium to large list opened (sometimes it doesn't even matter the size of the list being viewed). This second issue is what I'm currently trying to resolve.

Sounds like you got the root-causes found, excellent :+1: 

Just wanted to chip in that I also experience slowness with an album with 1000-2000 songs using [version 0.49.3](https://github.com/navidrome/navidrome/releases/tag/v0.49.3) (8b93962f) and the latest version of Firefox. Looking at 'top' on my Pi 3 and my desktop, the issue I have is that the browsertab uses 100% (1 CPU core) for a short while, which causes a delay of at least 15 seconds and then general slowness.  Setting ND_DEVACTIVITYPANEL to "false" did nothing for me unfortunately. If you have another ticket for the New UI, I'd be keen on subscribing to that ;-)

**Comment by cameronbroe** [comment]
> Thanks @metalheim, I think we have two different but related issues here: Large albums like that causes the browser to freeze/crash because the way React renders grids and tables. I'm trying to address this in the new UI with a virtual grid (like virtuoso.dev)
> 
> The second issue is that in some circumstances the browser opens multiple EventStream connections (used by the ActivityPanel) with the server. This causes a high overhead of cpu usage, specially when a scan is happening and/or you have a medium to large list opened (sometimes it doesn't even matter the size of the list being viewed). This second issue is what I'm currently trying to resolve.

I have encountered the first case extremely consistently with an album that has 4188 tracks in it. Getting all of https://ocremix.org has everything dumped in the same album tag, so it ends up being a ridiculously huge album. I've got a local branch where I adapted the AlbumShow and AlbumList components to use pagination like playlists and it seems to fix that problem at least. I don't know if you'd want me to PR that change as a temporary measure to at least keep the UI from going completely dead if someone has a scenario like this?

**Comment by VlaK0r** [comment]
ND_DEVACTIVITYPANEL: false 
It didn't help.

**Comment by raudraido** [comment]
This bug still exists with both Firefox and Chrome. Only solution right now is to disable activity panel

**Comment by snuq** [comment]
Ran into this issue with 0.51.1 and a 191 song album.... setting ND_DEVACTIVITYPANEL = false fixes it... but now im not sure how i can rescan the library :\

**Comment by deluan** [comment]
There are two different, but related issues reported here:
1. The Activity Panel may cause freezes in some browsers and some network conditions. This is an issue (that I was not able to identify the cause) with SSE (used by ND to send events to the browser). When scanning your library, the server sends one event for each folder analyzed, which may cause the browser to choke. I just pushed a change ([80acfc1](https://github.com/navidrome/navidrome/commit/80acfc103f72ed810014713a96e7e807a8e0bc19)) to reduce the number of events sent by a factor of 10. This should alleviate/eliminate the issue for the majority of the users. Another option is to disable it altogether, with `DevActivityPanel=false`.

2. Large albums (>200 songs) may cause the UI to become unresponsive. This is an issue with React-Admin when rendering large tables. As we will be rewriting the UI in the coming months, I don't want to spend too much time fixing this in the current UI. Possible workarounds:
   - Use a different client. There are [plenty of Subsonic clients](https://www.navidrome.org/docs/overview/#apps) out there, some Web-based examples: Feishin, Airsonic Refix and Aonsoku, and they seem to handle large albums better than the current Navidrome UI.
   - Another option is to not have an album with hundreds or thousands of songs in it! I know this shouldn't be a limitation, but Navidrome was created with the intent of handling _real_ albums, that _usually_ have less than 300 songs. If you want to create a playlist of songs, do that: Create a playlist. I know that there are valid, _real life_ albums with more than 300 songs, but they are rare instances, and we will be taking this into consideration in the next version of the UI

Having said all that, I'll close this ticket for now, as both issues will be fixed in the new UI, and there are workarounds in this comment.
