### ISSUE TITLE
Agent not available

### ISSUE THREAD

**Issue by un99known99** [navidrome/navidrome#1552]
### Description
In /var/log/syslog error message:
Jan  1 13:02:10 raspberrypi navidrome[468]: time="2022-01-01T13:02:10+01:00" level=error msg="Agent not available. Check configuration" name=spotify

### Expected Behaviour
no error log entry

### Platform information

 - Navidrome version: v0.47
 - Browser and version: Firefox v95.0.2
 - Operating System: Buster, Linux 5.10.63-v7, raspberian

**Comment by Dnouv** [comment]
@un99known99, thanks for reporting the issue. You are getting this message due to an incorrect Spotify Client ID or secret.
For additional details, you can refer to the following webpage,
[https://www.navidrome.org/docs/usage/configuration-options/](url)

**Comment by un99known99** [comment]
Hi Dnouv, thx for ur reply. Sry for not supplying the whole information, I had disabled all LastFM and Spotify settings in /var/lib/navidrome/navidrome.toml like
# LastFM.Enabled = "true"
# LastFM.ApiKey = "YYY"
# LastFM.Secret = "YYY"
# LastFM.Language = "de"
# Spotify.ID = "XXX"
# Spotify.Secret = "XXX"
# DevListenBrainzEnabled = "true"

**Comment by un99known99** [comment]
also set EnableExternalServices = "false"

**Comment by Dnouv** [comment]
No worries, @un99known99, I have a question why did you set the `Spotify.ID`  if you'd already set the `EnableExternalServices` as `false`?

If you don't require the LastFM and Spotify services in Navidrome, there is no need to add
`LastFM.Enabled` or `LastFM.ApiKey` 

The navidrome.toml would like something like this,

```
MusicFolder = "../nmusic"
LogLevel = "error"
DevAutoCreateAdminPassword = "password"
EnableExternalServices=false
``` 

Please feel free to comment if I missed something or misunderstood your issue.
Thank you!

PS. I just noticed the link to config options was broken, my bad, it's working now [here](https://www.navidrome.org/docs/usage/configuration-options/).

**Comment by un99known99** [comment]
many thanks for coming back, I did have enabled it for testing purposes, then I reverted back all "external" accesses, that why the spotify and other stuff have been "#" commented out

**Comment by Dnouv** [comment]
Do you see this line (All external services disabled...) in the logs of your setup?
```
6:13:37 PM GO.1 |  | \ | |           (_)   | |
6:13:37 PM GO.1 |  |  \| | __ ___   ___  __| |_ __ ___  _ __ ___   ___
6:13:37 PM GO.1 |  | . ` |/ _` \ \ / / |/ _` | '__/ _ \| '_ ` _ \ / _ \
6:13:37 PM GO.1 |  | |\  | (_| |\ V /| | (_| | | | (_) | | | | | |  __/
6:13:37 PM GO.1 |  \_| \_/\__,_| \_/ |_|\__,_|_|  \___/|_| |_| |_|\___|
6:13:37 PM GO.1 |                                          Version: dev

====================================
6:13:37 PM GO.1 |  INFO[0000] All external integrations are DISABLED!  <--------This line

==================================
6:13:37 PM GO.1 |  INFO[0000] goose: no migrations to run. current version: 20211105162746
6:13:37 PM GO.1 |  INFO[0000] Configuring Media Folder                      name="Music Library" path=../nmusic
```

**Comment by un99known99** [comment]
![grafik](https://user-images.githubusercontent.com/1615207/148080150-b5f06b30-3ac4-4c34-be33-00a0b74c5f1e.png)
yes

**Comment by un99known99** [comment]
6208 Jan  4 15:15:17 raspberrypi navidrome[487]: time="2022-01-04T15:15:17+01:00" level=info msg="Last.FM integration is DISABLED"
6209 Jan  4 15:15:17 raspberrypi navidrome[487]: time="2022-01-04T15:15:17+01:00" level=info msg="Spotify integration is not enabled: missing ID/Secret"
6210 Jan  4 15:15:17 raspberrypi navidrome[487]: time="2022-01-04T15:15:17+01:00" level=info msg="Mounting Native API routes" path=/api
6211 Jan  4 15:15:17 raspberrypi navidrome[487]: time="2022-01-04T15:15:17+01:00" level=error msg="Agent not available. Check configuration" name=lastfm
6212 Jan  4 15:15:17 raspberrypi navidrome[487]: time="2022-01-04T15:15:17+01:00" level=info msg="Creating Transcoding cache" maxSize="100 MB" path=/var/lib/navidrome/data/cache/transcoding
6213 Jan  4 15:15:17 raspberrypi navidrome[487]: time="2022-01-04T15:15:17+01:00" level=error msg="Agent not available. Check configuration" name=spotify

**Comment by srichter** [comment]
You can ignore the error; it's normal when Spotify is not configured. It was silenced in https://github.com/navidrome/navidrome/commit/20cdd38fc4dd9a87172758a6aa090c8d3f501c3f

**Comment by deluan** [comment]
Hey @un99known99, as @srichter mentioned this is a harmless message and was already fixed in master. Will close this as it was already solved, but feel free to reopen if you have any other concerns.

**Comment by un99known99** [comment]
Hi, just updated to 0.47.5 but still have the issue
level=error msg="Agent not available. Check configuration" name=spotify

Has that not been fixed in this release?
